/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iqbal_ndkhello_ndk_NativeLib */

#ifndef _Included_com_iqbal_ndkhello_ndk_NativeLib
#define _Included_com_iqbal_ndkhello_ndk_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iqbal_ndkhello_ndk_NativeLib
 * Method:    getHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iqbal_ndkhello_ndk_NativeLib_getHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
